#!/bin/bash
set -e

source /configs/identity.conf

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE $IDENTITY_DB;
  CREATE USER $IDENTITY_USR WITH ENCRYPTED PASSWORD '$IDENTITY_PW';
  REVOKE ALL ON SCHEMA public FROM $IDENTITY_USR;
  ALTER DATABASE $IDENTITY_DB OWNER TO $IDENTITY_USR;
  GRANT ALL PRIVILEGES ON DATABASE $IDENTITY_DB TO $IDENTITY_USR;
EOSQL
