#!/bin/bash
set -e

source /configs/media.conf

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $MEDIA_DB;
  CREATE USER $MEDIA_USR WITH ENCRYPTED PASSWORD '$MEDIA_PW';
  REVOKE ALL ON SCHEMA public FROM $MEDIA_USR;
  ALTER DATABASE $MEDIA_DB OWNER TO $MEDIA_USR;
  GRANT ALL PRIVILEGES ON DATABASE $MEDIA_DB TO $MEDIA_USR;
EOSQL
