#!/bin/bash
set -e

source /configs/record.conf

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $RECORD_DB;
  CREATE USER $RECORD_USR WITH ENCRYPTED PASSWORD '$RECORD_PW';
  REVOKE ALL ON SCHEMA public FROM $RECORD_USR;
  ALTER DATABASE $RECORD_DB OWNER TO $RECORD_USR;
  GRANT ALL PRIVILEGES ON DATABASE $RECORD_DB TO $RECORD_USR;
EOSQL
