services:
  wekode.mml.db:
    image: ${IMAGE}
    container_name: wekode.mml.db
    restart: always
    user: ${UID}:${GID}
    environment:
      POSTGRES_PASSWORD_FILE: /secrets/${POSTGRES_PASSWORD_FILE}
      POSTGRES_USER_FILE: /secrets/${POSTGRES_USER_FILE}
      PGDATA: /data
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256 --encoding=UTF8
    command: -c 'config_file=/etc/postgresql/mml-postgresql.conf'
    volumes:
      - ${PGDATA_VOL}:/data
      - ${SECRETS_VOL}:/secrets:ro
      - ${PG_CONFIG_VOL}:/etc/postgresql/mml-postgresql.conf:ro
      - ${DB_CONFIG_VOL}:/configs:ro
      - /etc/localtime:/etc/localtime:ro
      - ./initdb.d:/docker-entrypoint-initdb.d
    networks:
      - wekode.mml
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

networks:
  wekode.mml:
    external: true
